version: "3.3"
services:
  # this container copies in the project code and runs the app with uwsgi
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod.api
    depends_on:
      - "memcached"
    command: uwsgi --ini uwsgi.ini
    volumes:
      - /srv/certs:/certs:ro
      - badgr_server_api_staticfiles:/badgr_server/staticfiles
      - badgr_server_api_mediafiles:/badgr_server/mediafiles
    expose:
      - "5000"

  # this container runs memcached
  memcached:
    image: "bitnami/memcached:latest"
    expose:
      - "11211"

  # this container runs nginx (webserver) and uses the uwsgi app.sock file from prod_api via a volume
  nginx:
    container_name: badgr-server
    build:
      context: .
      dockerfile: .docker/Dockerfile.nginx
    volumes:
      - badgr_server_api_staticfiles:/badgr_server/staticfiles
      - badgr_server_api_mediafiles:/badgr_server/mediafiles
    depends_on:
      - "api"
    expose:
      - "80"

volumes:
  badgr_server_api_staticfiles:
  badgr_server_api_mediafiles:
